//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdmissionDocumentList
    {
        public int AdmissionDocumentList_ID { get; set; }
        public string DocumentCode { get; set; }
        public string DocumentName { get; set; }
        public Nullable<bool> IsDigital { get; set; }
        public Nullable<bool> IsMandatory { get; set; }
        public Nullable<bool> ToFollow { get; set; }
        public string FollowupTypeCode { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
