//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateDetail
    {
        public int CandidateDetail_ID { get; set; }
        public Nullable<int> Enquiry_ID { get; set; }
        public Nullable<int> AdmissionClass_id { get; set; }
        public Nullable<int> LastPassClass_ID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Lastname { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Email { get; set; }
        public Nullable<int> StudentType_ID { get; set; }
        public string ContactMobileNo { get; set; }
        public string HomePhone { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<bool> hasSibiling { get; set; }
        public string SiblingAdmNumber_ID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State_ID { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Landmark { get; set; }
        public string DistanceFromSchool { get; set; }
        public Nullable<int> Caste_ID { get; set; }
        public Nullable<int> Religon_ID { get; set; }
        public string FatheFirstName { get; set; }
        public string FatherMiddleName { get; set; }
        public string FatherLasttName { get; set; }
        public Nullable<int> FatherQualificaiton_ID { get; set; }
        public string FatherQualificaitonText { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherOfficeAddres { get; set; }
        public string FatherOrgnisation { get; set; }
        public string FatherDesignation { get; set; }
        public string MotherFirstName { get; set; }
        public string MotherMiddleName { get; set; }
        public string MotherLasttName { get; set; }
        public Nullable<int> MotherQualificaiton_Id { get; set; }
        public string MotherQualificaitonText { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherOfficeAddres { get; set; }
        public string MotherOrgnisation { get; set; }
        public string MotherDesignation { get; set; }
        public string CurrentSchool { get; set; }
        public string CurrentSchoolCity { get; set; }
        public string IsGovtTransfer { get; set; }
        public string Remarks { get; set; }
        public string CommunicationMode { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    
        public virtual CastCategory CastCategory { get; set; }
        public virtual ClassMaster ClassMaster { get; set; }
        public virtual ClassMaster ClassMaster1 { get; set; }
        public virtual Enquiry Enquiry { get; set; }
        public virtual Qualificaton Qualificaton { get; set; }
        public virtual Qualificaton Qualificaton1 { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
