//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentSubmission
    {
        public int DocumentSub_ID { get; set; }
        public Nullable<int> Document_ID { get; set; }
        public Nullable<int> Enquiry_Id { get; set; }
        public Nullable<int> Application_ID { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string PathofDocument { get; set; }
        public string PhysicalFileLocaiton { get; set; }
        public Nullable<int> SumissionMethod { get; set; }
        public Nullable<bool> OnlineDocumentVerified { get; set; }
        public Nullable<int> Sessionyear { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedBy_ID { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> ModifiedBy_ID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual DocumentSubmission DocumentSubmission1 { get; set; }
        public virtual DocumentSubmission DocumentSubmission2 { get; set; }
        public virtual Enquiry Enquiry { get; set; }
    }
}
