//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GEE.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMaster
    {
        public int School_ID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SchoolCode { get; set; }
        public string SchoolName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State_ID { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string Landmark { get; set; }
        public string SchoolEmail { get; set; }
        public string SchoolOwner { get; set; }
        public string OwnerMobile { get; set; }
        public string SchoolPrincipal { get; set; }
        public string SchoolPhone { get; set; }
        public Nullable<System.DateTime> BillingStart { get; set; }
        public Nullable<bool> ISActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> ISDeleted { get; set; }
    }
}
